# Generated by Django 3.0.7 on 2020-06-08 08:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JustBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('MG', 'Medical Ground'), ('PAR', 'Parent working in Govt / PSU/ Corporation got transferred'), ('CLO', 'clouser of course/ college')], max_length=3, verbose_name='Reason For Transfer')),
                ('trtype', models.CharField(choices=[('WITHIN', 'With in the same university affiliated colleges'), ('INTER', 'Inter University affiliated colleges'), ('OTHER', 'Others')], max_length=10, verbose_name='Type of Transfer')),
                ('regno', models.CharField(max_length=20, verbose_name='Reg. No /Admission No')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Candidate')),
                ('father', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('year', models.IntegerField(verbose_name='Year of Admission')),
                ('course', models.CharField(choices=[('C1', 'COURSE1'), ('C2', 'COURSE2')], max_length=3)),
                ('branch', models.CharField(default='TF', max_length=3)),
                ('prclass', models.CharField(choices=[('Cl1', 'CLASS1'), ('Cl2', 'CLASS2')], max_length=3, verbose_name='Present Studying Class')),
                ('auniv', models.CharField(choices=[('U1', 'UNIVERSITY1'), ('U2', 'UNIVERSITY2')], max_length=3, verbose_name='Affiliated University')),
                ('prdistrict', models.CharField(choices=[('D1', 'DISTRICT1'), ('D2', 'DISTRICT2')], max_length=3, verbose_name='District of Present Studying College')),
                ('prcollege', models.CharField(choices=[('Co1', 'COLLEGE1'), ('Co2', 'COLLEGE2')], max_length=3, verbose_name='Present Studying College')),
                ('prnoc_number', models.CharField(default='3aa2c798-c90c-4846-abb4-a611b2534607', max_length=100, verbose_name='NOC Number for Present College')),
                ('prnoc_date', models.DateField()),
                ('issued', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='TF', max_length=3)),
                ('district', models.CharField(choices=[('D1', 'DISTRICT1'), ('D2', 'DISTRICT2')], max_length=3, verbose_name='District of Seeking College')),
                ('college', models.CharField(choices=[('Co1', 'COLLEGE1'), ('Co2', 'COLLEGE2')], max_length=3, verbose_name='Present Seeking College')),
                ('sauniv', models.CharField(choices=[('U1', 'UNIVERSITY1'), ('U2', 'UNIVERSITY2')], max_length=3, verbose_name='Seeking Affiliated University')),
                ('snoc_number', models.CharField(default='3ad05a23-c872-44d2-85b7-4da43e125748', max_length=100, verbose_name='NOC Number for Seeking College')),
                ('snoc_date', models.DateField()),
                ('doc', models.FileField(upload_to='', verbose_name='Supporting Document')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('under', models.BooleanField(verbose_name='Accept')),
            ],
        ),
    ]
